version: '3.8'

services:
  heroflicksbackend:
    image: heroflicksbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3007:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: docker_user
      DB_PASSWORD: usuario
      DB_NAME: heroflicks
      PORT: 3000
      JWT_SECRET: mySecureRandomSecretKey1234567890!
    depends_on:
      db:
        condition: service_healthy
    networks:
      - comic-network

  db:
    image: mysql:8.0
    restart: always
    # --- LÍNEA NUEVA AÑADIDA ---
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroflicks
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: usuario
    volumes:
      - ./public/comics:/usr/src/app/public/comics
      - mysql_data:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - comic-network
    healthcheck:
      # --- LÍNEA CORREGIDA ---
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "docker_user", "-pusuario"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  comic-network:
    driver: bridge

volumes:
  mysql_data: