services:
  heroflicksbackend:
    image: heroflicksbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3007:3007
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
